// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJbCd5vPhexBHtoDfxE5UEFVoUwpVn8o',
    appId: '1:642116540552:web:a630fda3988bc6523ae73d',
    messagingSenderId: '642116540552',
    projectId: 'career-ai-shahed',
    authDomain: 'career-ai-shahed.firebaseapp.com',
    storageBucket: 'career-ai-shahed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPjSGbEnJtOtyO900xeavOCPxciquL_C8',
    appId: '1:642116540552:android:1b6a53e3762a18a63ae73d',
    messagingSenderId: '642116540552',
    projectId: 'career-ai-shahed',
    storageBucket: 'career-ai-shahed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxeEJpGHxs37VijHPWxTY_bGzyZFM9mxY',
    appId: '1:642116540552:ios:1b880053bcf3fa423ae73d',
    messagingSenderId: '642116540552',
    projectId: 'career-ai-shahed',
    storageBucket: 'career-ai-shahed.firebasestorage.app',
    iosBundleId: 'com.example.careerAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxeEJpGHxs37VijHPWxTY_bGzyZFM9mxY',
    appId: '1:642116540552:ios:1b880053bcf3fa423ae73d',
    messagingSenderId: '642116540552',
    projectId: 'career-ai-shahed',
    storageBucket: 'career-ai-shahed.firebasestorage.app',
    iosBundleId: 'com.example.careerAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGJbCd5vPhexBHtoDfxE5UEFVoUwpVn8o',
    appId: '1:642116540552:web:0a35eb8a0b75e2543ae73d',
    messagingSenderId: '642116540552',
    projectId: 'career-ai-shahed',
    authDomain: 'career-ai-shahed.firebaseapp.com',
    storageBucket: 'career-ai-shahed.firebasestorage.app',
  );
}
