import 'package:flutter/material.dart';
import 'package:open_filex/open_filex.dart';
import 'package:share_plus/share_plus.dart';

import '../services/ai_api_service.dart';
import '../services/local_storage_service.dart';
import '../theme/app_theme.dart';
import 'roadmap_screen.dart';

class UserDashboard extends StatefulWidget {
  const UserDashboard({super.key});

  @override
  State<UserDashboard> createState() => _UserDashboardState();
}

class _UserDashboardState extends State<UserDashboard> {
  double matchScore = 0.0;
  List<String> acquiredSkills = [];
  List<String> missingSkills = [];
  String userName = "Career Trainee";
  bool isLoading = true;
  bool hasCvAnalysisData = false;
  String savedCvText = "";

  Map<String, dynamic>? activeRoadmap;
  double roadmapProgress = 0.0;

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    try {
      final data = await LocalStorageService.getAnalysisData();
      final profile = await LocalStorageService.getUserProfile();
      
      // جلب المسار النشط من السيرفر
      final roadmapRes = await AiApiService.getActiveRoadmap();
      
      if (mounted) {
        setState(() {
          matchScore = data['matchScore'] ?? 0.0;
          acquiredSkills = data['acquiredSkills'] ?? [];
          missingSkills = data['missingSkills'] ?? [];
          savedCvText = data['cvText'] ?? "";
          userName = profile['name'] ?? "Career Trainee";
          hasCvAnalysisData = acquiredSkills.isNotEmpty || missingSkills.isNotEmpty || matchScore > 0.0;
          
          if (roadmapRes != null && roadmapRes['success'] == true) {
            activeRoadmap = roadmapRes['data'];
            _calculateRoadmapProgress();
          } else {
            activeRoadmap = null;
          }
          
          isLoading = false;
        });
      }
    } catch (e) {
      debugPrint("Dashboard Data Error: $e");
      if (mounted) {
        setState(() => isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Sync Error: $e"), backgroundColor: Colors.orange),
        );
      }
    }
  }

  void _calculateRoadmapProgress() {
    if (activeRoadmap == null) return;
    final total = (activeRoadmap!['missing_skills'] as List).length;
    final completed = (activeRoadmap!['completed_skills'] as List).length;
    if (total > 0) {
      roadmapProgress = completed / total;
    }
  }

  Future<void> _generateAtsCvFromSavedData() async {
    if (mounted) {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (_) => const Center(child: CircularProgressIndicator()),
      );
    }

    final result = await AiApiService.generateAtsCv(
      savedCvText,
      [...acquiredSkills, ...missingSkills],
    );

    if (mounted) Navigator.pop(context);

    if (result != null && !result.startsWith("Error:")) {
      if (!mounted) return;
      showDialog(
        context: context,
        builder: (context) => AlertDialog(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          title: const Row(
            children: [
              Icon(Icons.check_circle, color: Colors.green, size: 30),
              SizedBox(width: 10),
              Text("Success!", style: TextStyle(fontWeight: FontWeight.bold)),
            ],
          ),
          content: const Text("Your ATS-friendly CV has been generated successfully. What would you like to do?"),
          actions: [
            TextButton.icon(
              onPressed: () {
                Navigator.pop(context);
                OpenFilex.open(result);
              },
              icon: const Icon(Icons.picture_as_pdf, color: AppTheme.primaryColor),
              label: const Text("Open CV", style: TextStyle(color: AppTheme.primaryColor)),
            ),
            ElevatedButton.icon(
              onPressed: () {
                Navigator.pop(context);
                Share.shareXFiles([XFile(result)], text: "Here is my new ATS CV generated by CareerAI!");
              },
              icon: const Icon(Icons.share, color: Colors.white),
              label: const Text("Share / Save", style: TextStyle(color: Colors.white)),
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.primaryColor,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
            ),
          ],
        ),
      );
    } else if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed: ${result ?? "Unknown error"}')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FA),
      body: SafeArea(
        child: isLoading
            ? const Center(child: CircularProgressIndicator())
            : RefreshIndicator(
                onRefresh: _loadData,
                child: SingleChildScrollView(
                  physics: const AlwaysScrollableScrollPhysics(),
                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 20),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      _buildHeader(context),
                      const SizedBox(height: 24),
                      _buildAiInsight(context),
                      const SizedBox(height: 24),
                      _buildStats(context),
                      const SizedBox(height: 32),
                      _buildRoadmapSection(context),
                      const SizedBox(height: 32),
                      if (acquiredSkills.isNotEmpty || missingSkills.isNotEmpty)
                        _buildSkillsProgress(),
                      const SizedBox(height: 32),
                      _buildActions(context),
                    ],
                  ),
                ),
              ),
      ),
    );
  }

  // 🔹 Header
  Widget _buildHeader(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text("Welcome back 👋", style: TextStyle(fontSize: 16, color: Colors.black54)),
            const SizedBox(height: 4),
            Text(
              userName,
              style: TextStyle(
                fontSize: 22,
                fontWeight: FontWeight.bold,
                color: AppTheme.primaryColor,
              ),
            ),
          ],
        ),
        GestureDetector(
          onTap: () {
            Navigator.pushNamed(context, '/personProfile');
          },
          child: const CircleAvatar(
            radius: 20,
            backgroundColor: Color(0xFFE3F2FD),
            child: Icon(Icons.person, color: Colors.blue),
          ),
        )
      ],
    );
  }

  // 🔹 AI Insight (Dynamic)
  Widget _buildAiInsight(BuildContext context) {
    String message = "Upload a CV to let AI analyze your career path 🚀";
    if (missingSkills.isNotEmpty) {
      message = "AI suggests improving: ${missingSkills.take(2).join(', ')} 🔥";
    } else if (acquiredSkills.isNotEmpty) {
      message = "You have all the required skills! Generate your ATS CV now 🌟";
    }

    return GestureDetector(
      onTap: () {
        if (missingSkills.isNotEmpty) {
           // Go to roadmap
        } else {
           Navigator.pushNamed(context, '/uploadCV');
        }
      },
      child: Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [Color(0xFF0052FF), Color(0xFF6B00FF)],
          ),
          borderRadius: BorderRadius.circular(20),
        ),
        child: Row(
          children: [
            const Icon(Icons.auto_awesome, color: Colors.white),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                message,
                style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
              ),
            ),
            const Icon(Icons.arrow_forward_ios, color: Colors.white, size: 16)
          ],
        ),
      ),
    );
  }

  // 🔹 Stats (Dynamic)
  Widget _buildStats(BuildContext context) {
    return Row(
      children: [
        _card("Match Score", "${(matchScore * 100).toInt()}%", Icons.analytics, Colors.blue),
        const SizedBox(width: 16),
        _card("Acquired Skills", "${acquiredSkills.length}", Icons.verified, Colors.green),
      ],
    );
  }

  Widget _card(String title, String value, IconData icon, Color color) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.02),
              blurRadius: 10,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Column(
          children: [
            Icon(icon, color: color, size: 28),
            const SizedBox(height: 10),
            Text(value, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            Text(title, style: const TextStyle(fontSize: 12)),
          ],
        ),
      ),
    );
  }

  // 🔹 Skills Progress (Dynamic & Redesigned 🔥)
  Widget _buildSkillsProgress() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (acquiredSkills.isNotEmpty) ...[
          const Text("Acquired Skills", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
          const SizedBox(height: 12),
          Wrap(
            spacing: 10,
            runSpacing: 10,
            children: acquiredSkills.map((skill) => Chip(
              label: Text(skill, style: const TextStyle(fontWeight: FontWeight.w600, color: Colors.green)),
              backgroundColor: Colors.green.shade50,
              side: BorderSide(color: Colors.green.shade200),
              avatar: const Icon(Icons.check_circle, color: Colors.green, size: 18),
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
            )).toList(),
          ),
          const SizedBox(height: 24),
        ],
        if (missingSkills.isNotEmpty) ...[
          const Text("Skills to Master", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
          const SizedBox(height: 12),
          ...missingSkills.map((skill) => _missingSkillCard(skill)),
        ]
      ],
    );
  }

  Widget _missingSkillCard(String name) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: AppTheme.primaryColor.withOpacity(0.1),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.lock_clock_outlined, color: AppTheme.primaryColor, size: 20),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Text(
              name,
              style: const TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.w600,
                color: AppTheme.textPrimaryColor,
              ),
            ),
          ),
          const SizedBox(width: 12),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
            decoration: BoxDecoration(
              color: Colors.orange.shade50,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.orange.shade200),
            ),
            child: Text(
              "Pending",
              style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.bold,
                color: Colors.orange.shade700,
              ),
            ),
          ),
        ],
      ),
    );
  }

  // 🔹 Roadmap Section (Dynamic & Persistent)
  Widget _buildRoadmapSection(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text("Your Career Journey", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
        const SizedBox(height: 16),
        Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(20),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.03),
                blurRadius: 15,
                offset: const Offset(0, 5),
              ),
            ],
            border: Border.all(color: Colors.grey.shade100),
          ),
          child: activeRoadmap != null 
            ? _activeRoadmapContent(context)
            : _emptyRoadmapContent(context),
        ),
      ],
    );
  }

  Widget _activeRoadmapContent(BuildContext context) {
    return Column(
      children: [
        Row(
          children: [
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: AppTheme.primaryColor.withOpacity(0.1),
                borderRadius: BorderRadius.circular(12),
              ),
              child: const Icon(Icons.rocket_launch_rounded, color: AppTheme.primaryColor),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    activeRoadmap!['target_job'] ?? "Career Path",
                    style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                  ),
                  Text(
                    "You are on the right track!",
                    style: TextStyle(color: Colors.grey.shade500, fontSize: 12),
                  ),
                ],
              ),
            ),
            Text(
              "${(roadmapProgress * 100).toInt()}%",
              style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.primaryColor),
            ),
          ],
        ),
        const SizedBox(height: 20),
        ClipRRect(
          borderRadius: BorderRadius.circular(10),
          child: LinearProgressIndicator(
            value: roadmapProgress,
            minHeight: 8,
            backgroundColor: AppTheme.primaryColor.withOpacity(0.1),
            valueColor: const AlwaysStoppedAnimation(AppTheme.primaryColor),
          ),
        ),
        const SizedBox(height: 20),
        SizedBox(
          width: double.infinity,
          child: ElevatedButton(
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => RoadmapScreen(
                    targetJob: activeRoadmap!['target_job'],
                    missingSkills: const [], // Fetch from server
                  ),
                ),
              ).then((_) => _loadData());
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.primaryColor,
              foregroundColor: Colors.white,
              elevation: 0,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
            child: const Text("Continue Learning"),
          ),
        ),
      ],
    );
  }

  Widget _emptyRoadmapContent(BuildContext context) {
    return Column(
      children: [
        const Icon(Icons.map_outlined, size: 40, color: Colors.grey),
        const SizedBox(height: 12),
        const Text(
          "No active roadmap yet",
          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black54),
        ),
        const SizedBox(height: 8),
        const Text(
          "Upload your CV to generate your personalized career path",
          textAlign: TextAlign.center,
          style: TextStyle(color: Colors.grey, fontSize: 13),
        ),
        const SizedBox(height: 16),
        TextButton(
          onPressed: () => Navigator.pushNamed(context, '/uploadCV'),
          child: const Text("Get Started Now"),
        )
      ],
    );
  }

  // 🔹 Actions
  Widget _buildActions(BuildContext context) {
    return Column(
      children: [
        _actionButton("Upload New CV", Icons.upload, () {
          Navigator.pushNamed(context, '/uploadCV');
        }),
        if (hasCvAnalysisData) ...[
          const SizedBox(height: 14),
          _actionButton("Generate ATS CV", Icons.description, () {
            _generateAtsCvFromSavedData();
          }),
        ],
      ],
    );
  }

  Widget _actionButton(String text, IconData icon, VoidCallback onTap) {
    return ElevatedButton.icon(
      onPressed: onTap,
      icon: Icon(icon),
      label: Text(text),
      style: ElevatedButton.styleFrom(
        minimumSize: const Size(double.infinity, 50),
        backgroundColor: const Color(0xFF0052FF),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      ),
    );
  }
}